### ISSUE TITLE
Anvil Deploy Error

### ISSUE THREAD

**Issue by zkRWA** [iden3/contracts#322]
**A local blockchain deployment of the contracts help greatly with developers. Steps are followed for Anvil local chain deployment and here are the results with some errors. Could they be fixed please or any guide for fixing them locally is greatly appreciated:**
 Deploying Create2AnchorAddress...
Create2AddressAnchor deployed to: 0x56fF81aBB5cdaC478bF236db717e4976b2ff841e
Deploying Libraries contracts...
[✓] Poseidon1Element deployed to: 0xC72D76D7271924a2AD54a19D216640FeA3d138d9
[✓] Poseidon2Element deployed to: 0x72F721D9D5f91353B505207C63B56cF3d9447edB
[✓] Poseidon3Element deployed to: 0x5Bc89782d5eBF62663Df7Ce5fb4bc7408926A240
[✓] Poseidon4Element deployed to: 0x0695cF2c6dfc438a4E40508741888198A6ccacC2
[ 'deploying with CREATE2 strategy...' ]
[✓] SmtLib deployed to:  0x682364078e26C1626abD2B95109D2019E241F0F6
Deploying State contract...
[ '======== State: deploy started ========' ]
[ 'found defaultIdType 0x0112 for chainId 31337' ]
[ 'deploying Groth16VerifierStateTransition...' ]
[✓] Groth16VerifierStateTransition contract deployed to address 0x0165878A594ca255338adfa4d48449f69242Eb8F from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[ 'deploying StateLib...' ]
[✓] StateLib deployed to:  0xa513E6E4b8f2a923D98304ec87F64353C4D5C853
[ 'deploying StateCrossChainLib...' ]
[✓] StateCrossChainLib deployed to:  0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6
[ 'deploying CrossChainProofValidator...' ]
[✓] CrossChainProofValidator deployed to: 0x8A791620dd6260079BF849Dc5567aDC3F2FdC318
[ 'deploying State...' ]
[ 'deploying with CREATE2 strategy...' ]
Waiting for 1 confirmations to not interfere with Hardhat Ignition
Warning: Potentially unsafe deployment of contracts/state/State.sol:State

    You are using the `unsafeAllow.external-library-linking` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

[✓] State contract deployed to address 0xaea923d71Bc5ED3A622D4DfCF2f9C338889b1c70 from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[ '======== State: deploy completed ========' ]
Deploying Identity Tree Store contract...
[ 'deploying with CREATE2 strategy...' ]
Warning: Potentially unsafe deployment of contracts/identitytreestore/IdentityTreeStore.sol:IdentityTreeStore

    You are using the `unsafeAllow.external-library-linking` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

[✓] 
IdentityTreeStore deployed to: 0x8A38f3D19437f03c254F1CCDED0F161C507d8597
Deploying Create2AnchorAddress...
Create2AddressAnchor deployed to: 0x56fF81aBB5cdaC478bF236db717e4976b2ff841e
Deploying Libraries contracts...
[⚠] Poseidon1Element found already deployed to: 0xC72D76D7271924a2AD54a19D216640FeA3d138d9
[⚠] Poseidon2Element found already deployed to: 0x72F721D9D5f91353B505207C63B56cF3d9447edB
[⚠] Poseidon3Element found already deployed to: 0x5Bc89782d5eBF62663Df7Ce5fb4bc7408926A240
[⚠] Poseidon4Element found already deployed to: 0x0695cF2c6dfc438a4E40508741888198A6ccacC2
[ 'deploying with CREATE2 strategy...' ]
[⚠] SmtLib found already deployed to:  0x682364078e26C1626abD2B95109D2019E241F0F6
Deploying State contract...
[ '======== State: deploy started ========' ]
[ 'found defaultIdType 0x0112 for chainId 31337' ]
[ 'deploying Groth16VerifierStateTransition...' ]
[✓] Groth16VerifierStateTransition contract deployed to address 0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1 from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[ 'deploying StateLib...' ]
[✓] StateLib deployed to:  0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE
[ 'deploying StateCrossChainLib...' ]
[✓] StateCrossChainLib deployed to:  0x68B1D87F95878fE05B998F19b66F4baba5De1aed
[ 'deploying CrossChainProofValidator...' ]
[✓] CrossChainProofValidator deployed to: 0x3Aa5ebB10DC797CAC828524e59A333d0A371443c
[ 'deploying State...' ]
[ 'deploying with CREATE2 strategy...' ]
Waiting for 1 confirmations to not interfere with Hardhat Ignition
Warning: Potentially unsafe deployment of contracts/state/State.sol:State

    You are using the `unsafeAllow.external-library-linking` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

[✓] State contract deployed to address 0xaea923d71Bc5ED3A622D4DfCF2f9C338889b1c70 from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[ '======== State: deploy completed ========' ]
Deploying Identity Tree Store contract...
[ 'deploying with CREATE2 strategy...' ]
Warning: Potentially unsafe deployment of contracts/identitytreestore/IdentityTreeStore.sol:IdentityTreeStore

    You are using the `unsafeAllow.external-library-linking` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

[✓] 
IdentityTreeStore deployed to: 0x8A38f3D19437f03c254F1CCDED0F161C507d8597
Deploying Validators contracts...
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierMTPWrapper Wrapper deployed to: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] CredentialAtomicQueryMTPV2Validator deployed to: 0x9BEa30D38fDf56a9a350630410553517098C3435
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierSigWrapper Wrapper deployed to: 0xc5a5C42992dECbae36851359345FE25997F5C42d
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] CredentialAtomicQuerySigV2Validator deployed to: 0x23B5C6B61E74ebbdE1Bb28B703bA953462D52Ff2
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierV3Wrapper Wrapper deployed to: 0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] CredentialAtomicQueryV3Validator deployed to: 0x3002273c19093694D8A3eaCC0c87947eC389D8F7
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierAuthV2Wrapper Wrapper deployed to: 0x851356ae760d987E095750cCeb3bC6014560891C
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] AuthV2Validator deployed to: 0x43c152c690596eC28b5360385526d63cd3233D92
Deploying Universal Verifier contract...
[✓] VerifierLib deployed to:  0x70e0bA845a1A0F2DA3359C97E0285013525FFC49
Waiting for 1 confirmations to not interfere with Hardhat Ignition
[ 'deploying with CREATE2 strategy...' ]
Warning: Potentially unsafe deployment of contracts/verifiers/UniversalVerifier.sol:UniversalVerifier

    You are using the `unsafeAllow.external-library-linking` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

[✓] UniversalVerifier deployed to: 0xBFfA8819DdC14e88793A25d07Db342221062bf4E
Adding Validators to Universal Verifier...
Adding validators to Universal Verifier...
Error: could not decode result data (value="0x", info={ "method": "isWhitelistedValidator", "signature": "isWhitelistedValidator(address)" }, code=BAD_DATA, version=6.13.2)
    at makeError (/home/king/contracts/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at assert (/home/king/contracts/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at Interface.decodeFunctionResult (/home/king/contracts/node_modules/ethers/src.ts/abi/interface.ts:916:15)
    at staticCallResult (/home/king/contracts/node_modules/ethers/src.ts/contract/contract.ts:346:35)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async staticCall (/home/king/contracts/node_modules/ethers/src.ts/contract/contract.ts:303:24)
    at async Proxy.isWhitelistedValidator (/home/king/contracts/node_modules/ethers/src.ts/contract/contract.ts:351:41)
    at async main (/home/king/contracts/scripts/maintenance/addValidatorsToUniversalVerifier.ts:35:27) {
  code: 'BAD_DATA',
  value: '0x',
  info: {
    method: 'isWhitelistedValidator',
    signature: 'isWhitelistedValidator(address)'
  },
  shortMessage: 'could not decode result data'
}
Deployment completed successfully.
./deploy.sh: line 56: dators: command not found
Deploying Validators contracts...
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierMTPWrapper Wrapper deployed to: 0x8f86403A4DE0BB5791fa46B8e795C547942fE4Cf
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] CredentialAtomicQueryMTPV2Validator deployed to: 0x9BEa30D38fDf56a9a350630410553517098C3435
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierSigWrapper Wrapper deployed to: 0x36C02dA8a0983159322a80FFE9F24b1acfF8B570
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] CredentialAtomicQuerySigV2Validator deployed to: 0x23B5C6B61E74ebbdE1Bb28B703bA953462D52Ff2
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierV3Wrapper Wrapper deployed to: 0x1291Be112d480055DaFd8a610b7d1e203891C274
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] CredentialAtomicQueryV3Validator deployed to: 0x3002273c19093694D8A3eaCC0c87947eC389D8F7
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] Groth16VerifierAuthV2Wrapper Wrapper deployed to: 0xCD8a1C3ba11CF5ECfa6267617243239504a98d90
[ 'deploying with CREATE2 strategy...' ]
Mining 1 blocks not to interfere with Hardhat Ignition
[✓] AuthV2Validator deployed to: 0x43c152c690596eC28b5360385526d63cd3233D92
Deploying Universal Verifier contract...
[✓] VerifierLib deployed to:  0x7969c5eD335650692Bc04293B07F5BF2e7A673C0
Waiting for 1 confirmations to not interfere with Hardhat Ignition
[ 'deploying with CREATE2 strategy...' ]
Warning: Potentially unsafe deployment of contracts/verifiers/UniversalVerifier.sol:UniversalVerifier

    You are using the `unsafeAllow.external-library-linking` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

[✓] UniversalVerifier deployed to: 0xBFfA8819DdC14e88793A25d07Db342221062bf4E
Adding Validators to Universal Verifier...
Adding validators to Universal Verifier...
Error: could not decode result data (value="0x", info={ "method": "isWhitelistedValidator", "signature": "isWhitelistedValidator(address)" }, code=BAD_DATA, version=6.13.2)
    at makeError (/home/king/contracts/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at assert (/home/king/contracts/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at Interface.decodeFunctionResult (/home/king/contracts/node_modules/ethers/src.ts/abi/interface.ts:916:15)
    at staticCallResult (/home/king/contracts/node_modules/ethers/src.ts/contract/contract.ts:346:35)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async staticCall (/home/king/contracts/node_modules/ethers/src.ts/contract/contract.ts:303:24)
    at async Proxy.isWhitelistedValidator (/home/king/contracts/node_modules/ethers/src.ts/contract/contract.ts:351:41)
    at async main (/home/king/contracts/scripts/maintenance/addValidatorsToUniversalVerifier.ts:35:27) {
  code: 'BAD_DATA',
  value: '0x',
  info: {
    method: 'isWhitelistedValidator',
    signature: 'isWhitelistedValidator(address)'
  },
  shortMessage: 'could not decode result data'
}
Deployment completed successfully.

**Comment by zkRWA** [comment]
**The deployment script is as following:**
#!/bin/bash

# Define the network
NETWORK="localhost"

# Deploy create2AnchorAddress
echo "Deploying Create2AnchorAddress..."
npx hardhat run scripts/deploy/deployCreate2AddressAnchor.ts --network $NETWORK

# Deploy libraries contracts
echo "Deploying Libraries contracts..."
npx hardhat run scripts/deploy/deployLibraries.ts --network $NETWORK

# Deploy State contract
echo "Deploying State contract..."
npx hardhat run scripts/deploy/deployState.ts --network $NETWORK

# Deploy Identity Tree Store contract
echo "Deploying Identity Tree Store contract..."
npx hardhat run scripts/deploy/deployIdentityTreeStore.ts --network $NETWORK

# Deploy Vali#!/bin/bash

# Define the network
NETWORK="localhost"

# Deploy create2AnchorAddress
echo "Deploying Create2AnchorAddress..."
npx hardhat run scripts/deploy/deployCreate2AddressAnchor.ts --network $NETWORK

# Deploy libraries contracts
echo "Deploying Libraries contracts..."
npx hardhat run scripts/deploy/deployLibraries.ts --network $NETWORK

# Deploy State contract
echo "Deploying State contract..."
npx hardhat run scripts/deploy/deployState.ts --network $NETWORK

# Deploy Identity Tree Store contract
echo "Deploying Identity Tree Store contract..."
npx hardhat run scripts/deploy/deployIdentityTreeStore.ts --network $NETWORK

# Deploy Validators contracts
echo "Deploying Validators contracts..."
npx hardhat run scripts/deploy/deployValidators.ts --network $NETWORK

# Deploy Universal Verifier contract
echo "Deploying Universal Verifier contract..."
npx hardhat run scripts/deploy/deployUniversalVerifier.ts --network $NETWORK

# Add validators to whitelisted validators in Universal Verifier
echo "Adding Validators to Universal Verifier..."
npx hardhat run scripts/maintenance/addValidatorsToUniversalVerifier.ts --network $NETWORK

echo "Deployment completed successfully."
dators contracts
echo "Deploying Validators contracts..."
npx hardhat run scripts/deploy/deployValidators.ts --network $NETWORK

# Deploy Universal Verifier contract
echo "Deploying Universal Verifier contract..."
npx hardhat run scripts/deploy/deployUniversalVerifier.ts --network $NETWORK

# Add validators to whitelisted validators in Universal Verifier
echo "Adding Validators to Universal Verifier..."
npx hardhat run scripts/maintenance/addValidatorsToUniversalVerifier.ts --network $NETWORK

echo "Deployment completed successfully."
